apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  selector:
    matchLabels:
      app: deployment
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: deployment
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx
        image: shalinishalu0817/team-3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          successThreshold: 1
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: "service-capstone"
spec:
  selector:
    app: deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
